### PR TITLE
update Readme

### PR DESCRIPTION
**Pull request by ORESoftware**
it's important to update this, thanks for your work to create this functionality in the first place

### CODE REVIEW

**Comment by saadtazi** [comment]
Thanks for taking the time to submit a PR. 
I didn't get a chance to update the README myself. 
One clarification: you can still use firefox-profile is you don't use the official selenium-webdriver package. For example, it is useful if you use wd.js or wwbdriver.io packages... (which are other implentations of the selenium json wire protocol...)

**Comment by saadtazi** [comment]
I just updated the README... and I am working on fixing the `encoded()` (to make it error first...). Thanks for the feedback

**Comment by ORESoftware** [comment]
@saadtazi that is good to know, I might use webdriver.io and wd in the future, for now I am just using selenium-webdriver for NPM

**Comment by saadtazi** [comment]
To be precise: for `webdriver.io`, if you need a firefox profile, you need to install this [package](https://github.com/webdriverio/wdio-firefox-profile-service)... which depends on `firefox-profile` package.

**Pull request closed without merging**
