### PR TITLE
archive.bulk -> archive.glob

### PR DESCRIPTION
**Pull request by zdglagola**
In reference to https://github.com/saadtazi/firefox-profile-js/issues/79

### CODE REVIEW

**Comment by zdglagola** [comment]
sorry @saadtazi , not familiar with using encrypted keys w/travis. The extensions spec is failing with bad sauce labs credentials.

"""
Sauce Labs Authentication Error.\nYou used username \'SAUCE_USERNAME\' and access key \'SAUCE_ACCESS_KEY\' to authenticate
"""

**Comment by saadtazi** [comment]
No worries. It's a known issue (in this repo): PRs always fail :(

I'll take a look at your PRs later tonight. Thank you!

**Comment by saadtazi** [comment]
Reviewed the code from my phone. Merging now. Will release new version later

**Comment by saadtazi** [comment]
just published firefox-profile@0.4.8. Thank you so much!

**Comment by zdglagola** [comment]
Happy to help :)

**Pull request merged**
