### PR TITLE
fix existing user preferences parsing

### PR DESCRIPTION
**Pull request by cadorn**
More flexible parser and fixes to make it work with latest nodejs.

### CODE REVIEW

**Comment by cadorn** [comment]
$feature https://github.com/firephp/firephp-for-firebug.next/issues/1

**Comment by saadtazi** [comment]
Thanks for contributing. I will look at this tonight (EST).

**Comment by saadtazi** [comment]
Just published 0.3.8.

**Comment by saadtazi** [comment]
Just released 0.3.9 because I realized that I had some unnecessary event listeners that I removed to prevent memory leaks.
FYI: while adding you as a contributor in package.json, I found out that [your website](http://christophdorn.com/) is down (found on your github profile).

**Comment by cadorn** [comment]
@saadtazi Thanks for the heads up. The site is back. Need to update it though ...

**Pull request merged**
